# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build-ui:
    docker:
    - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: 
          working_directory: ~/project
          name: Install
          command: |
            npm install
      - run: 
          working_directory: ~/project
          name: Build
          command: |
            npm run build
workflows:
    build-ui:
      jobs:
        - build-ui
